exclude: |
    (?x)^(
    )$
repos:
-   repo: https://github.com/checkmake/checkmake.git
    rev: 0.2.2
    hooks:
    - id: checkmake
      exclude: |
        (?x)^(
          fixtures/missing_phony\.make
        )$
